spring.application.name=aura-api
server.port=5010

spring.datasource.url=jdbc:mysql://localhost:3306/aura_db?createDatabaseIfNotExist=true
spring.datasource.username=dev
spring.datasource.password=P@$$w0rd

# Como o banco MySQL já está pronto e não queremos alterar a estrutura do seu amigo, usamos 'none'
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Diretório para salvar as imagens localmente (Substituindo o Multer)
file.upload-dir=storage

# Aumentar o limite de upload de arquivos (padrão do Spring é 1MB e pode travar fotos maiores)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB